// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // This will auto-generate the sidebar from the docs folder structure
    },
  ],
};

module.exports = sidebars;